name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  ghcr-publish:
    name: Push Docker Image to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create Installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_EXT: ghcr.io/imnotjames/talos.extension.dell-poweredge-thermals
          TALOS_VERSION: 1.10
          ARCH: amd64
          PROFILE: installer
        run: |
          docker run \
            --rm \
            -t \
            -v /dev:/dev \
            --privileged \
            -e GITHUB_TOKEN=${GH_TOKEN} \
            -v "$PWD/_out:/out" \
            "ghcr.io/siderolabs/imager:${TALOS_VERSION}" \
            --arch "${ARCH}" \
            --system-extension-image ${IMAGE_EXT}:main \
            installer

          docker load -i ./_out/installer-${ARCH}.tar

          docker tag \
            ghcr.io/siderolabs/installer:${TALOS_VERSION} \
            ${IMAGE_EXT}/installer:${TALOS_VERSION}

          docker push ${IMAGE_EXT}/installer:${TALOS_VERSION}